name: Check for Updates

on:
  schedule:
      - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Summer2025-Internships repository
        uses: actions/checkout@v2
        with:
          repository: SimplifyJobs/Summer2025-Internships
          path: summer2025

      - name: Checkout New-Grad-Positions repository
        uses: actions/checkout@v2
        with:
          repository: SimplifyJobs/New-Grad-Positions
          path: new-grad

      - name: Checkout personal repository
        uses: actions/checkout@v2
        with:
          repository: seanlewertow/discord-job-listings-bot
          path: personal-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Check for updates in Summer2025-Internships listings.json
        id: check_internship_updates
        run: |
          # Download the current listings.json
          curl -o current_internship_listings.json https://raw.githubusercontent.com/SimplifyJobs/Summer2025-Internships/dev/.github/scripts/listings.json

          # Compare with the previous version
          if [ -f "personal-repo/.github/data/previous_internship_listings.json" ] && cmp -s "current_internship_listings.json" "personal-repo/.github/data/previous_internship_listings.json"; then
            echo "No changes detected in Summer2025-Internships listings.json."
            echo "no_changes_internship=true" >> $GITHUB_ENV
          else
            echo "Changes detected in Summer2025-Internships listings.json."
            echo "no_changes_internship=false" >> $GITHUB_ENV
            cp current_internship_listings.json personal-repo/.github/data/previous_internship_listings.json
          fi

      - name: Check for updates in New-Grad-Positions listings.json
        id: check_new_grad_updates
        run: |
          # Download the current listings.json
          curl -o current_new_grad_listings.json https://raw.githubusercontent.com/SimplifyJobs/New-Grad-Positions/dev/.github/scripts/listings.json

          # Compare with the previous version
          if [ -f "personal-repo/.github/data/previous_new_grad_listings.json" ] && cmp -s "current_new_grad_listings.json" "personal-repo/.github/data/previous_new_grad_listings.json"; then
            echo "No changes detected in New-Grad-Positions listings.json."
            echo "no_changes_new_grad=true" >> $GITHUB_ENV
          else
            echo "Changes detected in New-Grad-Positions listings.json."
            echo "no_changes_new_grad=false" >> $GITHUB_ENV
            cp current_new_grad_listings.json personal-repo/.github/data/previous_new_grad_listings.json
          fi

      - name: Trigger Internship Workflow
        if: env.no_changes_internship == 'false'
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/seanlewertow/discord-job-listings-bot/dispatches \
          -d '{"event_type":"internship_update_detected"}'

      - name: Trigger New Grad Workflow
        if: env.no_changes_new_grad == 'false'
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/seanlewertow/discord-job-listings-bot/dispatches \
          -d '{"event_type":"new_grad_update_detected"}'
