name: Notify Discord

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout job listings repository
        uses: actions/checkout@v2
        with:
          repository: SimplifyJobs/Summer2025-Internships # Public repository with job listings
          path: job-listings

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jq

      - name: Extract and Send job listings
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo 'import json, os' > script.py
          echo 'from pathlib import Path' >> script.py
          echo '' >> script.py
          echo '# Load the listings' >> script.py
          echo 'listings_path = Path("job-listings/.github/scripts/listings.json")' >> script.py
          echo 'with listings_path.open() as f:' >> script.py
          echo '    listings = json.load(f)' >> script.py
          echo '' >> script.py
          echo '# Process each listing' >> script.py
          echo 'for listing in listings:' >> script.py
          echo '    company_name = listing["company_name"]' >> script.py
          echo '    title = listing["title"]' >> script.py
          echo '    locations = ", ".join(listing["locations"])' >> script.py
          echo '    url = listing["url"]' >> script.py
          echo '    message = f"{company_name}: {title} in {locations} - [Apply Here]({url})"' >> script.py
          echo '    print(f"Sending message: {message}")' >> script.py
          echo '    os.system(f"curl -H \\"Content-Type: application/json\\" -X POST -d \\"{{\\"content\\": \\"{message}\\"}}\\" {os.getenv(\'DISCORD_WEBHOOK\')}")' >> script.py
          python script.py
