name: Notify Discord

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout job listings repository
        uses: actions/checkout@v2
        with:
          repository: SimplifyJobs/Summer2025-Internships # Public repository with job listings
          path: job-listings

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jq

      - name: Extract and Send job listings
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          cat <<EOF > script.py
import json
import os
from pathlib import Path

# Load the listings
listings_path = Path('job-listings/.github/scripts/listings.json')
with listings_path.open() as f:
    listings = json.load(f)

# Process each listing
for listing in listings:
    company_name = listing['company_name']
    title = listing['title']
    locations = ', '.join(listing['locations'])
    url = listing['url']
    message = f"{company_name}: {title} in {locations} - [Apply Here]({url})"
    print(f"Sending message: {message}")
    os.system(f'curl -H "Content-Type: application/json" -X POST -d "{{\\"content\\": \\"{message}\\"}}" {os.getenv("DISCORD_WEBHOOK")}')
EOF
          python script.py
