name: Notify Discord

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout job listings repository
        uses: actions/checkout@v2
        with:
          repository: SimplifyJobs/Summer2025-Internships # Public repository with job listings
          path: job-listings

      - name: Extract job listings
        id: extract_jobs
        run: |
          listings=$(cat job-listings/.github/scripts/listings.json)
          listings="${listings//'%'/'%25'}"
          listings="${listings//$'\n'/ }"
          echo "::set-output name=listings::$listings"

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          listings="${{ steps.extract_jobs.outputs.listings }}"
          echo "Listings: $listings"
          formatted_listings=$(echo "$listings" | jq -r '.[] | "\(.company_name): \(.title) in \(.locations | join(", ")) - [Apply Here](\(.url))"')
          if [[ -z "$formatted_listings" || "$formatted_listings" == "[]" ]]; then
            message="No new job listings available."
          else
            message="$formatted_listings"
          fi
          echo "Message: $message"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$message\"}" \
               $DISCORD_WEBHOOK
