name: Notify Discord

on:
  push:
    paths:
      - 'job-listings/.github/scripts/listings.json'
      - '.github/workflows/nsbe-discord-opportunities-bot.yml'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout job listings repository
        uses: actions/checkout@v2
        with:
          repository: SimplifyJobs/Summer2025-Internships # Public repository with job listings
          path: job-listings

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jq requests

      - name: Extract and Send job listings
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          cat << 'EOF' > script.py
          import json
          import os
          from datetime import datetime
          from pathlib import Path
          import requests

          # Load the listings
          listings_path = Path('job-listings/.github/scripts/listings.json')
          with listings_path.open() as f:
              listings = json.load(f)

          # Get the most recent listing (the last one in the JSON file)
          recent_listing = listings[-1]

          # Load the last sent listing
          last_listing_path = Path('.github/scripts/last_listing.json')
          if last_listing_path.exists():
              with last_listing_path.open() as f:
                  last_listing = json.load(f)
          else:
              last_listing = {}

          # Check if the recent listing is the same as the last sent listing
          if recent_listing == last_listing:
              message = "No new listings. The most recent listing has already been sent to Discord."
          else:
              # Extract listing details
              company_name = recent_listing['company_name']
              title = recent_listing['title']
              locations = ', '.join(recent_listing['locations'])
              url = recent_listing['url']
              date_posted = datetime.fromtimestamp(recent_listing['date_posted']).strftime('%Y-%m-%d')
              term = ', '.join(recent_listing['terms'])

              # Format the message
              message = (
                  f"**Company:** {company_name}\n"
                  f"**Role:** {title}\n"
                  f"**Location:** {locations}\n"
                  f"**Application/Link:** [Apply Here]({url})\n"
                  f"**Date Posted:** {date_posted}\n"
                  f"**Term:** {term}\n"
                  "---------------------------"
              )

              # Send the message to Discord
              response = requests.post(
                  os.getenv('DISCORD_WEBHOOK'),
                  json={'content': message}
              )

              # Raise an error if the request failed
              response.raise_for_status()

              # Save the recent listing to last_listing.json
              with last_listing_path.open('w') as f:
                  json.dump(recent_listing, f, indent=4)

          # Output the sent message
          print("\n--- Sent Listing ---")
          print(message)

          # Commit message for the listings
          commit_message = f"Updated listing sent to Discord: {title}" if recent_listing != last_listing else "No new listings sent to Discord."
          print(f"\n--- Commit Message ---\n{commit_message}")

          EOF
          python script.py
