name: Notify Discord

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    paths:
      - 'job-listings/.github/scripts/listings.json' # Triggers only when listings.json is updated
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout job listings repository
        uses: actions/checkout@v2
        with:
          repository: SimplifyJobs/Summer2025-Internships # Public repository with job listings
          path: job-listings

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jq

      - name: Extract and Send job listings
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          cat << 'EOF' > script.py
          import json
          import os
          from datetime import datetime
          from pathlib import Path

          # Load the listings
          listings_path = Path('job-listings/.github/scripts/listings.json')
          with listings_path.open() as f:
              listings = json.load(f)

          # Get the most recent listing (the last one in the JSON file)
          recent_listing = listings[-1]

          # Extract listing details
          company_name = recent_listing['company_name']
          title = recent_listing['title']
          locations = ', '.join(recent_listing['locations'])
          url = recent_listing['url']
          date_posted = datetime.fromtimestamp(recent_listing['date_posted']).strftime('%Y-%m-%d')
          terms = ', '.join(recent_listing['terms'])

          # Format the message
          message = (
              f"**Company:** {company_name}\n"
              f"**Role:** {title}\n"
              f"**Location:** {locations}\n"
              f"**Application/Link:** [Apply Here]({url})\n"
              f"**Date Posted:** {date_posted}\n"
              f"**Terms:** {terms}\n"
              "---------------------------"
          )

          # Send the message to Discord
          os.system(f'curl -H "Content-Type: application/json" -X POST -d "{{\\"content\\": \\"{message}\\"}}" {os.getenv("DISCORD_WEBHOOK")}')

          # Output the sent message
          print("\n--- Sent Listing ---")
          print(message)
          EOF
          python script.py
