name: Notify Discord

on:
  push:
    paths:
      - '.github/workflows/nsbe-discord-opportunities-bot.yml' # Triggers when this workflow file is updated
      - 'job-listings/.github/scripts/listings.json' # Triggers when the listings.json file is updated

jobs:
  sync_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v2

      - name: Fetch listings.json from SimplifyJobs repository
        run: |
          git clone --depth=1 https://github.com/SimplifyJobs/Summer2025-Internships.git temp_repo
          cp temp_repo/.github/scripts/listings.json job-listings/.github/scripts/listings.json
          rm -rf temp_repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Extract and Send job listings
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          cat << 'EOF' > script.py
          import json
          import os
          from datetime import datetime
          from pathlib import Path
          import requests

          # Paths to listings and last_sent files
          listings_path = Path('job-listings/.github/scripts/listings.json')
          last_sent_path = Path('job-listings/.github/scripts/last_sent.txt')

          # Load the listings
          with listings_path.open() as f:
              listings = json.load(f)

          # Get the most recent listing (the last one in the JSON file)
          recent_listing = listings[-1]

          # Extract listing details
          company_name = recent_listing['company_name']
          title = recent_listing['title']
          locations = ', '.join(recent_listing['locations'])
          url = recent_listing['url']
          date_posted = datetime.fromtimestamp(recent_listing['date_posted']).strftime('%Y-%m-%d')
          term = ', '.join(recent_listing['term'])

          # Format the message
          message = (
              f"**Company:** {company_name}\n"
              f"**Role:** {title}\n"
              f"**Location:** {locations}\n"
              f"**Application/Link:** [Apply Here]({url})\n"
              f"**Date Posted:** {date_posted}\n"
              f"**Term:** {term}\n"
              "---------------------------"
          )

          # Check if the last listing has been sent before
          if last_sent_path.exists():
              with last_sent_path.open() as f:
                  last_sent = f.read().strip()
          else:
              last_sent = ""

          if last_sent != title:
              # Send the message to Discord
              response = requests.post(
                  os.getenv('DISCORD_WEBHOOK'),
                  json={'content': message}
              )

              # Raise an error if the request failed
              response.raise_for_status()

              # Output the sent message
              print("\n--- Sent Listing ---")
              print(message)

              # Update the last_sent.txt file
              with last_sent_path.open('w') as f:
                  f.write(title)

              # Commit message for the listings
              commit_message = f"Updated listing sent to Discord: {title}"
              print(f"\n--- Commit Message ---\n{commit_message}")
          else:
              print("No new listings to send.")

          EOF
          python script.py

      - name: Commit the last sent listing
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add job-listings/.github/scripts/last_sent.txt
          git commit -m "Update last_sent.txt with the latest listing"
          git push
